package Concorde.Options is

   function Scenario return String;
   function Display_Language return String;
   function Faction_Name return String;
   function Console return Boolean;
   function Randomise return Boolean;
   function Create_Voronoi return Boolean;
   function Create_Galaxy return Boolean;
   function Create_Factions return Boolean;
   function Faction_Count return Natural;
   function System_Count return Natural;
   function Initial_Trade_Ships return Natural;
   function Update_Count return Natural;
   function Galaxy_Shape return String;
   function System_X_Deviation return Natural;
   function System_Y_Deviation return Natural;
   function System_Z_Deviation return Natural;
   function Average_Connections return Positive;
   function Full_Screen return Boolean;
   function Display_Width return Natural;
   function Display_Height return Natural;
   function Work_Threads return Positive;
   function Start_With_Galaxy return Boolean;
   function Enable_Faction_Logging return Boolean;
   function Enable_Market_Logging return Boolean;
   function Write_Accounts return Boolean;
   function Test_Battle return Boolean;
   function Create_Voronoi_Diagram return Boolean;
   function Realistic_Star_Masses return Boolean;
   function World_Detail_Factor return Positive;
   function World_Sector_Size return Positive;
   function World_Height_Smoothing return Positive;
   function Log_Folder return String;
   function Detailed_Logging return Boolean;
   function Show_Clock_Time return Boolean;
   function Update_Speed return Natural;
   function Log_Ship_Movement return Boolean;
   function Log_Trade_Offers return Boolean;
   function Political_Map_Mode return Boolean;

end Concorde.Options;
